version: "3"
services:
  jenkins:
    image: jenkins/jenkins:latest
    container_name: jenkins
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - data:/var/jenkins_home
    restart: always
volumes:
  data:
    driver: local